export const experienceData = [
  {
    company: "Wake Smiles",
    title: "Software Development Engineer, Co-op",
    date: "Jan. 2023 - May 2023",
    description:
      "I will be working on the Amazon Alexa team as a Software Development Engineer Intern.",
    link: "https://www.amazon.com/",
    used: [
      "Java",
      "Spring Boot",
      "AWS",
      "DynamoDB",
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
    ],
  },
  {
    company: "Amazon",
    title: "Software Development Engineer Intern",
    date: "Jun. 2022 - Sep. 2022",
    description:
      "I will be working on the Amazon Alexa team as a Software Development Engineer Intern.",
    link: "https://www.amazon.com/",
    used: [
      "Java",
      "Spring Boot",
      "AWS",
      "DynamoDB",
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
    ],
  },
  {
    company: "UNC Department of Computer Science",
    title: "Undergraduate Teaching Assistant, COMP 426 & COMP 301",
    date: "Aug. 2022 - Present",
    description:
      "I will be working on the Amazon Alexa team as a Software Development Engineer Intern.",
    link: "https://www.amazon.com/",
    used: ["React", "TypeScript", "JavaScript", "HTML", "CSS"],
  },
  {
    company: "Pearl Hacks",
    title: "Director of Promotion",
    date: "May. 2021 - May. 2022",
    description:
      "I will be working on the Amazon Alexa team as a Software Development Engineer Intern.",
    link: "https://www.amazon.com/",
    used: [
      "Java",
      "Spring Boot",
      "AWS",
      "DynamoDB",
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
    ],
  },
  {
    company: "IBM",
    title: "Software Development Acclerator Program, Team Lead",
    date: "May. 2021 - Aug. 2021",
    description:
      "I will be working on the Amazon Alexa team as a Software Development Engineer Intern.",
    link: "https://www.amazon.com/",
    used: [
      "Java",
      "Spring Boot",
      "AWS",
      "DynamoDB",
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
    ],
  },

  {
    company: "Pearl Hacks",
    title: "Director of Design",
    date: "May. 2020 - May. 2021",
    description:
      "I will be working on the Amazon Alexa team as a Software Development Engineer Intern.",
    link: "https://www.amazon.com/",
    used: [
      "Java",
      "Spring Boot",
      "AWS",
      "DynamoDB",
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
    ],
  },
];
